// test/noise.test.js —— S2 噪音分类器（纯函数 / 确定性 / 无 I/O）
//
// 验收口径（计划 ① 期 S2）：回归 fixture 四类样本分别标 high/high/high 或 low/none；活库 trailer-only 全 high；
// 断言针对 fixture 而非活库（活库只做「trailer-only 全部 high」这一条不变式断言）；同输入同输出。
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  NEAR_DUPLICATE_MIN_TOKENS, NOISE_LEVELS, NOISE_REASONS,
  classifyAtom, classifyAtoms, contentAfterNoise, hasTemplateLines, hasTrailerLines, noiseSummary,
} from '../lib/noise.js';
import { readAllAtoms } from '../lib/journal.js';

// ---------- 回归 fixture：trailer-only / 模板 / 重复 / 干净 四类样本 ----------
const FIXTURE = [
  // 0 trailer-only：why 剥掉 Co-Authored-By 后为空
  { id: 'commit:t1', ts: '2026-09-01T00:00:00Z', kind: 'commit', title: 'feat: a',
    why: 'Co-Authored-By: Bot <b@x.com>' },
  // 1 模板：why 全是生成器样板（剥 trailer 后仍非空 → 走 template-only 而不是 trailer-only）
  { id: 'commit:t2', ts: '2026-09-02T00:00:00Z', kind: 'commit', title: 'chore: b',
    why: 'Auto-generated by the release bot' },
  // 2 重复：同 title 同 why（有正文）→ duplicate-title + duplicate-why
  { id: 'commit:d1', ts: '2026-09-03T00:00:00Z', kind: 'commit', title: 'fix: same subject',
    why: 'same rationale text here' },
  { id: 'commit:d2', ts: '2026-09-04T00:00:00Z', kind: 'commit', title: 'fix: same subject',
    why: 'same rationale text here' },
  // 4 干净
  { id: 'commit:c1', ts: '2026-09-05T00:00:00Z', kind: 'commit', title: 'use ZSET for ranges',
    why: 'range queries stay O(logN) and need a single round trip' },
];
const [TRAILER_ONLY, TEMPLATE, DUP_A, DUP_B, CLEAN] = FIXTURE;

test('fixture 四类样本：trailer-only / 模板 / 重复 → high，干净 → none', () => {
  const res = classifyAtoms(FIXTURE);
  assert.equal(res.length, FIXTURE.length);
  assert.equal(res[0].level, 'high');
  assert.deepEqual(res[0].reasons, ['trailer-only']);
  assert.equal(res[1].level, 'high');
  assert.deepEqual(res[1].reasons, ['template-only']);
  assert.equal(res[2].level, 'high');                       // 重复摘要
  assert.ok(res[2].reasons.includes('duplicate-title'));
  assert.ok(res[2].reasons.includes('duplicate-why'));
  assert.equal(res[3].level, 'high');
  assert.equal(res[4].level, 'none');
  assert.deepEqual(res[4].reasons, []);
  // 级别与原因码都是白名单内取值
  for (const r of res) {
    assert.ok(NOISE_LEVELS.includes(r.level), r.level);
    for (const reason of r.reasons) assert.ok(NOISE_REASONS.includes(reason), reason);
  }
});

test('low 档：正文混 trailer / 混模板 / why 高度相似（token Jaccard）', () => {
  const mixed = [
    { id: 'commit:m1', ts: '2026-09-01T00:00:00Z', kind: 'commit', title: 'fix: m1',
      why: 'real reason\nCo-Authored-By: Bot <b@x.com>' },
    { id: 'commit:m2', ts: '2026-09-02T00:00:00Z', kind: 'commit', title: 'fix: m2',
      why: 'real reason\nGenerated by the release bot' },
    { id: 'commit:n1', ts: '2026-09-03T00:00:00Z', kind: 'commit', title: 'fix: n1',
      why: 'alpha beta gamma delta epsilon zeta eta theta iota kappa' },
    { id: 'commit:n2', ts: '2026-09-04T00:00:00Z', kind: 'commit', title: 'fix: n2',
      why: 'alpha beta gamma delta epsilon zeta eta theta iota lambda' },
  ];
  const res = classifyAtoms(mixed);
  assert.deepEqual(res[0], { level: 'low', reasons: ['trailer-mixed'] });
  assert.deepEqual(res[1], { level: 'low', reasons: ['template-mixed'] });
  assert.deepEqual(res[2], { level: 'low', reasons: ['near-duplicate-why'] });
  assert.deepEqual(res[3], { level: 'low', reasons: ['near-duplicate-why'] });
  // 短文本不参与近重复（阈值 NEAR_DUPLICATE_MIN_TOKENS），避免误报
  assert.equal(classifyAtoms([
    { title: 'a', why: 'too short' }, { title: 'b', why: 'too short' },
  ])[0].level, 'high');                                     // 但同 why 精确相等 → duplicate-why
  assert.ok(NEAR_DUPLICATE_MIN_TOKENS >= 8);
});

test('trailer / 模板的识别口径：contentAfterNoise 剥净后为空才算「无正文」', () => {
  assert.equal(contentAfterNoise('Co-Authored-By: Bot <b@x>'), '');
  assert.equal(contentAfterNoise('real\nCo-Authored-By: Bot <b@x>'), 'real');
  assert.equal(contentAfterNoise('no description'), '');
  assert.equal(contentAfterNoise('<describe why>'), '');
  assert.equal(hasTrailerLines('Signed-off-by: D <d@x>'), true);
  assert.equal(hasTrailerLines('real'), false);
  assert.equal(hasTemplateLines('Auto-generated by CI'), true);
  assert.equal(hasTemplateLines('update README with the new flag'), false);   // 真标题不误伤
  assert.equal(hasTemplateLines('generated with Codex'), false);              // 归 trailer 口径（stripTrailers 管）
});

test('纯函数：同输入同输出、顺序无关、不抛（坏输入降级 none）', () => {
  const a = classifyAtoms(FIXTURE);
  const b = classifyAtoms(FIXTURE.map(x => ({ ...x })));
  assert.deepEqual(b, a);                                    // 同输入同输出（不改入参、不用随机/挂钟）
  // 顺序无关：对组内每条都打标（不是"只标后来的"）→ 反序输入得到同样的逐条结果
  const reversed = [...FIXTURE].reverse();
  const r2 = classifyAtoms(reversed);
  FIXTURE.forEach((atom, i) => {
    assert.deepEqual(r2[reversed.indexOf(atom)], a[i], atom.id);
  });
  assert.deepEqual(classifyAtoms([]), []);
  assert.deepEqual(classifyAtom(null), { level: 'none', reasons: [] });
  assert.deepEqual(classifyAtom('nope'), { level: 'none', reasons: [] });
  assert.deepEqual(classifyAtom([]), { level: 'none', reasons: [] });
  assert.deepEqual(classifyAtom({ title: 't', why: 42 }), { level: 'none', reasons: [] });
});

test('无 I/O、不读挂钟：模块源码不 import fs/child_process、不用 Date/随机', () => {
  const src = readFileSync(join(process.cwd(), 'lib', 'noise.js'), 'utf8');
  // import 行单独看（注释里可以提到 node:fs，说明「本模块不 import 它」）
  const imports = src.split('\n').filter(l => /^\s*import\b/.test(l)).join('\n');
  for (const banned of ['node:fs', 'node:child_process', 'node:os', 'node:path']) {
    assert.equal(imports.includes(banned), false, `lib/noise.js 不应 import ${banned}`);
  }
  for (const banned of ['Date.now', 'new Date', 'Math.random', 'process.']) {
    assert.equal(src.includes(banned), false, `lib/noise.js 不应出现 ${banned}`);
  }
});

test('noiseSummary：分布计数 = 输入条数，reasons 逐码计数', () => {
  const s = noiseSummary(FIXTURE);
  assert.deepEqual({ high: s.high, low: s.low, none: s.none }, { high: 4, low: 0, none: 1 });
  assert.equal(s.high + s.low + s.none, FIXTURE.length);
  assert.equal(s.reasons['trailer-only'], 1);
  assert.equal(s.reasons['template-only'], 1);
  assert.equal(s.reasons['duplicate-title'], 2);
  assert.equal(s.reasons['duplicate-why'], 2);
  assert.equal(s.reasons['near-duplicate-why'], 0);
  assert.deepEqual(Object.keys(s.reasons).sort(), [...NOISE_REASONS].sort());   // 键集稳定（只增不改）
});

// ---------- 活库不变式：trailer-only 全部 high（只断言这一条，不钉死其它计数） ----------
test('活库：所有 trailer-only 原子都是 high（降权，不删除、不回填）', () => {
  const atoms = readAllAtoms(join(process.cwd(), '.lore', 'journal'));
  assert.ok(atoms.length > 0, 'journal 为空——活库断言失去意义');
  const trailerOnly = atoms.filter(a => typeof a.why === 'string' && a.why.trim() !== '' && contentAfterNoise(a.why) === '');
  assert.ok(trailerOnly.length > 0, '本仓库应有 trailer-only 存量（设计附录 B 口径）');
  const res = classifyAtoms(atoms);
  let checked = 0;
  atoms.forEach((a, i) => {
    if (typeof a.why === 'string' && a.why.trim() !== '' && contentAfterNoise(a.why) === '') {
      assert.equal(res[i].level, 'high', `${a.id} 应为 high（${JSON.stringify(res[i])}）`);
      checked++;
    }
  });
  assert.equal(checked, trailerOnly.length);                 // 运行时条数：检查数 = 活库 trailer-only 数
  const s = noiseSummary(atoms);
  assert.equal(s.high + s.low + s.none, atoms.length);
});
