// lib/migrate.js —— 期望态对齐器（spec 2026-06-11-lore-migrate-design）。
// 引擎升级后 repo 内资产自动收敛：收敛型「算期望→比实际→不同才写」；
// 一次性迁移记 .state/migrations.json（applied 后用户删除不复活——用户主权）。
import { existsSync, readFileSync, writeFileSync, copyFileSync, mkdirSync, chmodSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { installResident, refreshResident, residentStats, mergeMcpConfig } from './resident.js';
import { alignHostAssets, instructionFilesFor, readEnabledHosts, defaultHostsPath } from './host.js';
import { parseConfigResident, parseConfigCodeRoots } from './config.js';
import { discoverDocs } from './init.js';   // 循环 import（init→migrate 已存在）；仅函数体内运行时用，安全

const HERE = dirname(fileURLToPath(import.meta.url));

// ---------- 一次性迁移记录（best-effort：读坏 → 空，同 syncstate 风格） ----------
export function readMigrations(stateDir) {
  try {
    const j = JSON.parse(readFileSync(join(stateDir, 'migrations.json'), 'utf8'));
    return new Set(Array.isArray(j.applied) ? j.applied : []);
  } catch { return new Set(); }
}

export function appendMigration(stateDir, id) {
  const s = readMigrations(stateDir);
  s.add(id);
  mkdirSync(stateDir, { recursive: true });
  writeFileSync(join(stateDir, 'migrations.json'), JSON.stringify({ applied: [...s] }, null, 2) + '\n');
}

// ---------- 壳（收敛型）：引擎 site/ 是期望源；.lore/site/ 是引擎领地，手改会被覆盖 ----------
export const SHELL_FILES = ['index.html', 'shell.mjs', 'mermaid.min.js'];

export function alignShell(engineSiteDir, loreDir) {
  const dest = join(loreDir, 'site');
  mkdirSync(dest, { recursive: true });
  const actions = [];
  for (const f of SHELL_FILES) {
    const src = join(engineSiteDir, f);
    if (!existsSync(src)) continue;                    // 引擎缺该文件（如测试夹具）→ 跳过
    const dst = join(dest, f);
    const want = readFileSync(src);
    const had = existsSync(dst);
    if (had && want.equals(readFileSync(dst))) continue;
    copyFileSync(src, dst);
    actions.push({ asset: `shell:${f}`, action: had ? 'refreshed' : 'installed' });
  }
  return actions;
}

// ---------- hook stub（收敛型）：含 lore MARKER 才动；foreign 永不碰 ----------
export const HOOK_MARKER = '# lore:post-commit';

export function renderHookStub(hookJsPath) {
  const p = hookJsPath.replace(/\\/g, '/');            // forward-slash: sh-safe on Windows
  return `#!/bin/sh\n${HOOK_MARKER} (auto-generated by /lore:init)\nnode "${p}" "$(git rev-parse --show-toplevel)" >/dev/null 2>&1 || true\n`;
}

// 返回 {status}: installed|refreshed|present|absent|foreign|hookspath-set|no-git|disabled
// install:false（finalize 自动迁移的缺省）= 只刷新已装 stub（spec：含 MARKER 才动）；
// 首装仅 init 场景（install:true）——避免把 hook 塞进从未要过它的 repo。
export function alignHookStub(repoRoot, hookJsPath, configText = '', { install = false } = {}) {
  if (/^\s*hook:\s*false\b/m.test(configText)) return { status: 'disabled' };
  let gitCommonDir = '';
  try {
    gitCommonDir = execFileSync('git', ['rev-parse', '--git-common-dir'], { cwd: repoRoot, windowsHide: true })
      .toString().trim();
  } catch { return { status: 'no-git' }; }
  let hooksPath = '';
  try {
    hooksPath = execFileSync('git', ['config', '--get', 'core.hooksPath'], { cwd: repoRoot, windowsHide: true })
      .toString().trim();
  } catch { /* unset → empty */ }
  const defaultHooks = resolve(resolve(repoRoot, gitCommonDir), 'hooks');
  if (hooksPath && resolve(repoRoot, hooksPath) !== defaultHooks) return { status: 'hookspath-set' };
  const hookPath = join(defaultHooks, 'post-commit');
  const want = renderHookStub(hookJsPath);
  if (existsSync(hookPath)) {
    const cur = readFileSync(hookPath, 'utf8');
    if (!cur.includes(HOOK_MARKER)) return { status: 'foreign' };
    if (cur === want) return { status: 'present' };
    writeFileSync(hookPath, want);
    try { chmodSync(hookPath, 0o755); } catch { /* Windows ignores */ }
    return { status: 'refreshed' };
  }
  if (!install) return { status: 'absent' };
  mkdirSync(dirname(hookPath), { recursive: true });
  writeFileSync(hookPath, want);
  try { chmodSync(hookPath, 0o755); } catch { /* Windows ignores */ }
  return { status: 'installed' };
}

// ---------- resident 资产：instructionFiles 节 + .mcp.json lore 条目 ----------
// 已存在 → 收敛 refresh；缺失 → 一次性首装（applied 记录后用户删除不复活）。
// applied 键：CLAUDE.md 兼容旧键 resident:install；其余文件用 resident:install:<file> ——
// 后启用的新宿主（如 codex）在已 init 的 repo 上也能补装自己的 AGENTS.md。
const RESIDENT_ASSET = { 'CLAUDE.md': 'claude-md', 'AGENTS.md': 'agents-md' };

export function alignResidentAssets(repoRoot, loreDir, mcpJsPath, applied, recordFn, { hostsPath } = {}) {
  const actions = [];
  const stats = residentStats(loreDir);
  const files = instructionFilesFor(readEnabledHosts(hostsPath ?? defaultHostsPath()));
  const covered = f => applied.has(`resident:install:${f}`) || (f === 'CLAUDE.md' && applied.has('resident:install'));
  // loop 内 recordFn 会就地改 applied——mcp-json 首装判定先快照（旧 firstInstall 语义：进场时无记录 → 装一次并记录）。
  const mcpFirstInstall = !covered('CLAUDE.md');

  for (const f of files) {
    const p = join(repoRoot, f);
    const has = existsSync(p) && /<!--\s*LORE_RESIDENT:START\s*-->/.test(readFileSync(p, 'utf8'));
    if (has) {
      const before = readFileSync(p, 'utf8');
      refreshResident(repoRoot, stats, [f]);
      if (readFileSync(p, 'utf8') !== before) actions.push({ asset: RESIDENT_ASSET[f] ?? `resident:${f}`, action: 'refreshed' });
    } else if (!covered(f)) {
      installResident(repoRoot, stats, [f]);
      recordFn(`resident:install:${f}`);
      if (f === 'CLAUDE.md') recordFn('resident:install');            // 旧键同步记，兼容既有语义
      actions.push({ asset: RESIDENT_ASSET[f] ?? `resident:${f}`, action: 'installed' });
    }
  }

  // .mcp.json lore 条目：只在 claude 启用时管（codex/opencode 走机器层全局注册）；
  // 首装才装、用户删了不复活（旧语义：applied 无记录且条目缺失 → 装；已有条目 → 路径过期才刷）。
  if (files.includes('CLAUDE.md')) {
    const mcpPath = join(repoRoot, '.mcp.json');
    let mcpCfg = null;
    if (existsSync(mcpPath)) { try { mcpCfg = JSON.parse(readFileSync(mcpPath, 'utf8')); } catch { mcpCfg = null; } }
    const loreEntry = mcpCfg?.mcpServers?.lore;
    const wantEntry = { command: 'node', args: [mcpJsPath] };
    if (loreEntry) {
      if (JSON.stringify(loreEntry) !== JSON.stringify(wantEntry)) {
        mergeMcpConfig(repoRoot, mcpJsPath);
        actions.push({ asset: 'mcp-json', action: 'refreshed' });
      }
    } else if (mcpFirstInstall) {
      mergeMcpConfig(repoRoot, mcpJsPath);
      recordFn('resident:install');                                   // 条目首装也记旧键：删了不复活（节先已在、loop 未记的场景）
      actions.push({ asset: 'mcp-json', action: 'installed' });
    }
  }

  return actions;
}

// ---------- config 补缺块（一次性 per block）：已有行永不改一个字 ----------
// template 中 <component> 为示例组件占位，插入/拼装时替换。
// 注意：renderConfigYaml（init.js）从这些块拼装首生成模板——单一真源。
export const CONFIG_BLOCKS = [
  {
    id: 'config:language', level: 'top', key: 'language',
    detectRe: /^language:/m,
    template: `language:                    # wiki 语言（人读首页 + 双语 sidecar）
  default: en                # repo 主语言（改成 zh 则中文为主）
  available: [en]            # 已就绪语言；加 zh 启用中英双语翻译页`,
  },
  {
    id: 'config:axes.flow', level: 'axes', key: 'flow',
    detectRe: /^\s*flow:/m,
    template: `  flow:                      # 声明轴 — "数据怎么端到端跑"（示例，按需填）
    values: []
    # - { id: article-pipeline, spans: [<component>] }`,
  },
  {
    id: 'config:axes.theme', level: 'axes', key: 'theme',
    detectRe: /^\s*theme:/m,
    template: `  theme:                     # 自定义横切轴 — "这条长期主线怎么演进"（示例，按需填）
    values: []
    # - { id: quality, desc: "质量保证", match: [质量, accuracy, 误报] }`,
  },
  {
    id: 'config:axes.docs', level: 'axes', key: 'docs',
    detectRe: /^\s*docs:/m,
    template: `  docs:                      # 文档轴 — 把 docs/ + CHANGELOG + CLAUDE.md 收进 wiki（机械、物化视图、零 LLM）
    # sources: [docs, changelog, claude_md_pitfalls]
    # docs_glob: docs/**/*.md`,
  },
  {
    id: 'config:journal', level: 'top', key: 'journal',
    detectRe: /^journal:/m,
    template: `journal:
  hook: true                 # post-commit hook 已装（每 commit 写 journal 骨架原子）
  mine: [commits, changelog, claude_md_pitfalls]`,
  },
  {
    id: 'config:resident-note', level: 'top', key: null,
    detectRe: /^#?\s*resident:/m,
    template: `# resident: true             # CLAUDE.md 注入 + .mcp.json 注册开关（false 关；详见 README agent 常驻）`,
  },
];

// axes: 块的范围：标题行 + 之后连续的「空行/缩进行」；0 缩进非空行（含注释）为界。
function sliceAxesBlock(lines) {
  const start = lines.findIndex(l => /^axes:\s*(#.*)?$/.test(l));
  if (start < 0) return null;
  let end = start;
  for (let i = start + 1; i < lines.length; i++) {
    if (lines[i].trim() === '') continue;              // 块中空行：跳过但不收尾
    if (/^\s/.test(lines[i])) { end = i; continue; }
    break;
  }
  return { start, end };
}

export function alignConfig(loreDir, applied, recordFn) {
  const p = join(loreDir, 'config.yml');
  if (!existsSync(p)) return [];                       // 没 init 过 ≠ 迁移场景
  let text = readFileSync(p, 'utf8');
  const eol = text.includes('\r\n') ? '\r\n' : '\n';
  const sample = (parseConfigCodeRoots(text)[0] ?? 'module');
  const fill = t => t.replace('<component>', sample);
  const actions = [];

  for (const b of CONFIG_BLOCKS.filter(x => x.level === 'top')) {
    if (b.detectRe.test(text)) continue;
    if (applied.has(b.id)) continue;
    const sep = text.endsWith('\n') ? '' : eol;        // 不动已有尾部，只按需补换行
    text = text + sep + eol + fill(b.template).replace(/\n/g, eol) + eol;
    recordFn(b.id);
    actions.push({ asset: `config:+${b.key ?? 'resident-note'}`, action: 'appended' });
  }

  for (const b of CONFIG_BLOCKS.filter(x => x.level === 'axes')) {
    const lines = text.split(eol);
    const ax = sliceAxesBlock(lines);
    if (!ax) break;                                    // 锚缺 → 二级全 skip 且不记
    const body = lines.slice(ax.start + 1, ax.end + 1).join('\n');
    if (b.detectRe.test(body)) continue;
    if (applied.has(b.id)) continue;
    let tmpl = fill(b.template);
    // docs 轴特殊：repo 有专门文档目录 → 补「可用的真 glob」而非注释默认。
    // 这是 migrate 缺口的核心修复——早 init 的仓库，引擎后加 docs 自动发现，跑一次 finalize 即自动收 docs。
    if (b.key === 'docs') {
      const disc = discoverDocs(join(resolve(loreDir), '..'));
      if (disc.docsGlobs.length) {
        const srcs = ['docs', ...disc.metaDocs.map(m => m.kind), 'claude_md_pitfalls'];
        tmpl = `  docs:                      # 文档轴（引擎升级自动发现）${eol}    sources: [${srcs.join(', ')}]${eol}    docs_glob: ${disc.docsGlobs[0]}`;
      }
    }
    lines.splice(ax.end + 1, 0, ...tmpl.split(eol));
    text = lines.join(eol);
    recordFn(b.id);
    actions.push({ asset: `config:+axes.${b.key}`, action: 'inserted' });
  }

  if (actions.length) writeFileSync(p, text);
  return actions;
}

// ---------- git 边界（facts-only）：wiki/site 出库，journal/config 进库 ----------
export const GITIGNORE_LINES = ['.lore/.state/', '.lore/wiki/', '.lore/site/'];
const GITATTR_LINE = '.lore/journal/**/*.ndjson merge=union';

function appendLines(filePath, missing) {
  const cur = existsSync(filePath) ? readFileSync(filePath, 'utf8') : '';
  const sep = cur === '' || cur.endsWith('\n') ? '' : '\n';
  writeFileSync(filePath, cur + sep + missing.join('\n') + '\n');
}

export function alignGitignore(repoRoot, applied, recordFn) {
  const p = join(repoRoot, '.gitignore');
  const have = existsSync(p) ? readFileSync(p, 'utf8').split(/\r?\n/).map(l => l.trim()) : [];
  const todo = GITIGNORE_LINES.filter(l => !have.includes(l) && !applied.has(`gitignore:${l}`));
  if (!todo.length) return [];
  appendLines(p, todo);
  for (const l of todo) recordFn(`gitignore:${l}`);
  return todo.map(l => ({ asset: `gitignore:${l}`, action: 'appended' }));
}

export function alignGitattributes(repoRoot, applied, recordFn) {
  const id = 'gitattributes:journal-union';
  const p = join(repoRoot, '.gitattributes');
  const have = existsSync(p) ? readFileSync(p, 'utf8').split(/\r?\n/).map(l => l.trim()) : [];
  if (have.includes(GITATTR_LINE) || applied.has(id)) return [];
  appendLines(p, [GITATTR_LINE]);
  recordFn(id);
  return [{ asset: 'gitattributes', action: 'appended' }];
}

// ---------- 总入口（后续逐资产挂载；单资产失败不挡其他） ----------
export function alignAssets(repoRoot, loreDir, opts = {}) {
  const engineSiteDir = opts.engineSiteDir ?? join(HERE, '..', 'site');
  const hookJsPath = opts.hookJsPath ?? join(HERE, 'hook.js');
  const mcpJsPath = opts.mcpJsPath ?? join(HERE, 'mcp.js');
  const stateDir = join(loreDir, '.state');
  const applied = readMigrations(stateDir);
  const record = id => { appendMigration(stateDir, id); applied.add(id); };
  const actions = [];
  const guard = (name, fn) => {
    try { actions.push(...fn()); }
    catch { actions.push({ asset: name, action: 'error' }); }
  };

  guard('config', () => alignConfig(loreDir, applied, record));
  const cfgPath = join(loreDir, 'config.yml');
  const cfgText = existsSync(cfgPath) ? readFileSync(cfgPath, 'utf8') : '';   // config 对齐后再读

  guard('gitignore', () => alignGitignore(repoRoot, applied, record));
  guard('gitattributes', () => alignGitattributes(repoRoot, applied, record));
  guard('shell', () => alignShell(engineSiteDir, loreDir));
  guard('hook-stub', () => {
    const { status } = alignHookStub(repoRoot, hookJsPath, cfgText, { install: opts.installHook ?? false });
    return (status === 'installed' || status === 'refreshed') ? [{ asset: 'hook-stub', action: status }] : [];
  });
  if (parseConfigResident(cfgText)) {
    guard('resident', () => alignResidentAssets(repoRoot, loreDir, mcpJsPath, applied, record));
  }
  // 机器层宿主命令资产：漂移即重生成。opts.home 缺省 → 真 homedir()（init/finalize 生产路径现状）。
  guard('host', () => alignHostAssets({ home: opts.home }).map(a => ({ asset: `host:${a.host}`, action: a.action })));
  return actions;
}

export function formatActions(actions) {
  return actions.map(a => `${a.asset}:${a.action}`).join(', ');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const repoRoot = resolve(process.argv[2] ?? process.cwd());
  const loreDir = join(repoRoot, '.lore');
  if (!existsSync(loreDir)) {
    console.error(`no .lore at ${repoRoot} — run /lore:init first`);
    process.exit(1);
  }
  const actions = alignAssets(repoRoot, loreDir);
  if (actions.length) console.log('migrate: ' + formatActions(actions));
}
