// lib/migrate.js —— 期望态对齐器（spec 2026-06-11-lore-migrate-design）。
// 引擎升级后 repo 内资产自动收敛：收敛型「算期望→比实际→不同才写」；
// 一次性迁移记 .state/migrations.json（applied 后用户删除不复活——用户主权）。
import { existsSync, readFileSync, writeFileSync, copyFileSync, mkdirSync, chmodSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { installResident, refreshResident, residentStats, mergeMcpConfig } from './resident.js';
import { parseConfigResident } from './config.js';

const HERE = dirname(fileURLToPath(import.meta.url));

// ---------- 一次性迁移记录（best-effort：读坏 → 空，同 syncstate 风格） ----------
export function readMigrations(stateDir) {
  try {
    const j = JSON.parse(readFileSync(join(stateDir, 'migrations.json'), 'utf8'));
    return new Set(Array.isArray(j.applied) ? j.applied : []);
  } catch { return new Set(); }
}

export function appendMigration(stateDir, id) {
  const s = readMigrations(stateDir);
  s.add(id);
  mkdirSync(stateDir, { recursive: true });
  writeFileSync(join(stateDir, 'migrations.json'), JSON.stringify({ applied: [...s] }, null, 2) + '\n');
}

// ---------- 壳（收敛型）：引擎 site/ 是期望源；.lore/site/ 是引擎领地，手改会被覆盖 ----------
export const SHELL_FILES = ['index.html', 'shell.mjs', 'mermaid.min.js'];

export function alignShell(engineSiteDir, loreDir) {
  const dest = join(loreDir, 'site');
  mkdirSync(dest, { recursive: true });
  const actions = [];
  for (const f of SHELL_FILES) {
    const src = join(engineSiteDir, f);
    if (!existsSync(src)) continue;                    // 引擎缺该文件（如测试夹具）→ 跳过
    const dst = join(dest, f);
    const want = readFileSync(src);
    const had = existsSync(dst);
    if (had && want.equals(readFileSync(dst))) continue;
    copyFileSync(src, dst);
    actions.push({ asset: `shell:${f}`, action: had ? 'refreshed' : 'installed' });
  }
  return actions;
}

// ---------- hook stub（收敛型）：含 lore MARKER 才动；foreign 永不碰 ----------
export const HOOK_MARKER = '# lore:post-commit';

export function renderHookStub(hookJsPath) {
  const p = hookJsPath.replace(/\\/g, '/');            // forward-slash: sh-safe on Windows
  return `#!/bin/sh\n${HOOK_MARKER} (auto-generated by /lore:init)\nnode "${p}" "$(git rev-parse --show-toplevel)" >/dev/null 2>&1 || true\n`;
}

// 返回 {status}: installed|refreshed|present|foreign|hookspath-set|no-git|disabled
export function alignHookStub(repoRoot, hookJsPath, configText = '') {
  if (/^\s*hook:\s*false\b/m.test(configText)) return { status: 'disabled' };
  let gitCommonDir = '';
  try {
    gitCommonDir = execFileSync('git', ['rev-parse', '--git-common-dir'], { cwd: repoRoot, windowsHide: true })
      .toString().trim();
  } catch { return { status: 'no-git' }; }
  let hooksPath = '';
  try {
    hooksPath = execFileSync('git', ['config', '--get', 'core.hooksPath'], { cwd: repoRoot, windowsHide: true })
      .toString().trim();
  } catch { /* unset → empty */ }
  const defaultHooks = resolve(resolve(repoRoot, gitCommonDir), 'hooks');
  if (hooksPath && resolve(repoRoot, hooksPath) !== defaultHooks) return { status: 'hookspath-set' };
  const hookPath = join(defaultHooks, 'post-commit');
  const want = renderHookStub(hookJsPath);
  if (existsSync(hookPath)) {
    const cur = readFileSync(hookPath, 'utf8');
    if (!cur.includes(HOOK_MARKER)) return { status: 'foreign' };
    if (cur === want) return { status: 'present' };
    writeFileSync(hookPath, want);
    try { chmodSync(hookPath, 0o755); } catch { /* Windows ignores */ }
    return { status: 'refreshed' };
  }
  mkdirSync(dirname(hookPath), { recursive: true });
  writeFileSync(hookPath, want);
  try { chmodSync(hookPath, 0o755); } catch { /* Windows ignores */ }
  return { status: 'installed' };
}

// ---------- resident 资产：CLAUDE.md 节 + .mcp.json lore 条目 ----------
// 已存在 → 收敛 refresh；缺失 → resident:install 一次性首装（applied 后用户删除不复活）。
export function alignResidentAssets(repoRoot, loreDir, mcpJsPath, applied, recordFn) {
  const actions = [];
  const stats = residentStats(loreDir);
  const claudePath = join(repoRoot, 'CLAUDE.md');
  const mcpPath = join(repoRoot, '.mcp.json');
  const hasSection = existsSync(claudePath) && /<!--\s*LORE_RESIDENT:START\s*-->/.test(readFileSync(claudePath, 'utf8'));
  let mcpCfg = null;
  if (existsSync(mcpPath)) { try { mcpCfg = JSON.parse(readFileSync(mcpPath, 'utf8')); } catch { mcpCfg = null; } }
  const loreEntry = mcpCfg?.mcpServers?.lore;
  const firstInstall = (!hasSection || !loreEntry) && !applied.has('resident:install');

  // CLAUDE.md 节：在 → 刷（变了才报）；缺且首装 → install
  if (hasSection) {
    const before = readFileSync(claudePath, 'utf8');
    refreshResident(repoRoot, stats);
    if (readFileSync(claudePath, 'utf8') !== before) actions.push({ asset: 'claude-md', action: 'refreshed' });
  } else if (firstInstall) {
    installResident(repoRoot, stats);
    actions.push({ asset: 'claude-md', action: 'installed' });
  }

  // .mcp.json lore 条目：在 → 路径过期才刷；缺且首装 → 创建
  const wantEntry = { command: 'node', args: [mcpJsPath] };
  if (loreEntry) {
    if (JSON.stringify(loreEntry) !== JSON.stringify(wantEntry)) {
      mergeMcpConfig(repoRoot, mcpJsPath);
      actions.push({ asset: 'mcp-json', action: 'refreshed' });
    }
  } else if (firstInstall) {
    mergeMcpConfig(repoRoot, mcpJsPath);
    actions.push({ asset: 'mcp-json', action: 'installed' });
  }

  if (firstInstall) recordFn('resident:install');
  return actions;
}

// ---------- 总入口（后续逐资产挂载；单资产失败不挡其他） ----------
export function alignAssets(repoRoot, loreDir, opts = {}) {
  const engineSiteDir = opts.engineSiteDir ?? join(HERE, '..', 'site');
  const actions = [];
  const guard = (name, fn) => {
    try { actions.push(...fn()); }
    catch { actions.push({ asset: name, action: 'error' }); }
  };
  guard('shell', () => alignShell(engineSiteDir, loreDir));
  const hookJsPath = opts.hookJsPath ?? join(HERE, 'hook.js');
  const cfgPath = join(loreDir, 'config.yml');
  const cfgText = existsSync(cfgPath) ? readFileSync(cfgPath, 'utf8') : '';
  guard('hook-stub', () => {
    const { status } = alignHookStub(repoRoot, hookJsPath, cfgText);
    return (status === 'installed' || status === 'refreshed') ? [{ asset: 'hook-stub', action: status }] : [];
  });
  const stateDir = join(loreDir, '.state');
  const applied = readMigrations(stateDir);
  const record = id => { appendMigration(stateDir, id); applied.add(id); };
  const mcpJsPath = opts.mcpJsPath ?? join(HERE, 'mcp.js');
  if (parseConfigResident(cfgText)) {
    guard('resident', () => alignResidentAssets(repoRoot, loreDir, mcpJsPath, applied, record));
  }
  return actions;
}

export function formatActions(actions) {
  return actions.map(a => `${a.asset}:${a.action}`).join(', ');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const repoRoot = resolve(process.argv[2] ?? process.cwd());
  const loreDir = join(repoRoot, '.lore');
  if (!existsSync(loreDir)) {
    console.error(`no .lore at ${repoRoot} — run /lore:init first`);
    process.exit(1);
  }
  const actions = alignAssets(repoRoot, loreDir);
  if (actions.length) console.log('migrate: ' + formatActions(actions));
}
