// lib/noise.js —— S2 噪音分类器（纯函数 / 确定性 / 无 I/O / 不读挂钟；设计 §3.4 + 计划 ① 期 S2）
//
// 目的：把「可信」与「噪音」分开，**降权而不是删除**。设计 §3.4 明令禁止对历史 127 条 trailer-only
// 做 LLM 回填（伪造因果史比空白更有害），所以本模块只输出级别与原因，绝不改写、不回填、不删除原子。
//
// 三类噪音（对应计划 S2 的三个口径）：
//   trailer-only   why 剥掉 trailer 后为空（复用 lib/fold.js 的 stripTrailers——渲染/写入/分类同一份规则）
//   template-only  why（或 why 缺省时的 title）只由生成器/占位模板文本组成（"Generated with …"、"Generated by …"、"no description"）
//   duplicate      同 title / 同 why 高度相似（重复摘要）
//
// 级别（降权强度）：
//   high  trailer-only / template-only / duplicate-title / duplicate-why —— 该原子**没有人读的正文**
//   low   trailer-mixed / template-mixed / near-duplicate-why —— 有正文，但混着噪音或与另一条高度重复
//   none  干净
//
// 确定性：不读挂钟、不用随机、不依赖输入顺序（重复检测对**组内每条**打标，不是"只标后来的"，
// 所以同一集合换顺序分类结果不变）。I/O 一律没有——本模块不 import node:fs / child_process。
import { stripTrailers } from './fold.js';

export const NOISE_LEVELS = Object.freeze(['none', 'low', 'high']);
// 原因码是稳定契约（doctor / 后续章节 digest 消费）：只增不改语义。
export const NOISE_REASONS = Object.freeze([
  'trailer-only', 'trailer-mixed',
  'template-only', 'template-mixed',
  'duplicate-title', 'duplicate-why', 'near-duplicate-why',
]);

// 模板文本：窄口径，只抓**生成器/占位符**写法（宽口径会把 "update README" 这类真标题误伤）。
// 分两族：
//   TEMPLATE_RES       只由本模块识别（stripTrailers 不管），如 "Auto-generated by …"、"no description"；
//   GENERATOR_SIG_RE   生成器签名行（"🤖 Generated with [Claude Code](…)" / "Generated with Codex"）——
//                      stripTrailers **也会**剥掉它，所以必须先按模板判，否则会被错标成 trailer-only/trailer-mixed。
//                      口径依据：设计附录 B / 计划 S2 把「模板文本（如 "Generated with …"）」单列一类，
//                      trailer 一类指 `-by:` 家族（Co-Authored-By / Signed-off-by）。
const TEMPLATE_RES = [
  /^auto-?generated\b/i,
  /^this (?:commit|file|change|page|atom|entry) (?:was|is) (?:auto-?)?generated\b/i,
  /^(?:generated|created|authored|written) by\b/i,
  /^(?:no description|no rationale|no details?|n\/?a|tbd|todo|wip|fixme)\s*[.!]?$/i,
  /^<[^>]*>$/,                       // 纯占位符：<describe why>
  /^\.{3,}$/,
];
// 与 lib/fold.js 的 TRAILER_RES 第二条同源（生成器签名），但归类为**模板**而非 trailer。
const GENERATOR_SIG_RE = /^[^\p{L}\p{N}]*generated with\b/iu;

const isStr = v => typeof v === 'string';
const normText = s => String(s ?? '').toLowerCase().replace(/[\s\p{P}\p{S}]+/gu, ' ').trim();
const isTemplateLine = line => {
  const t = line.trim();
  return t !== '' && (TEMPLATE_RES.some(re => re.test(t)) || GENERATOR_SIG_RE.test(t));
};

// 一行是否 trailer（stripTrailers 的同一份规则，逐行问一遍——用于区分 only / mixed）。
// 先排除模板行：生成器签名行两边都命中，归属必须是 template（见 GENERATOR_SIG_RE 注释）。
const isTrailerLine = line => {
  const t = line.trim();
  return t !== '' && !isTemplateLine(line) && stripTrailers(t) === '';
};

export function hasTrailerLines(text) {
  return isStr(text) && text.split('\n').some(isTrailerLine);
}
export function hasTemplateLines(text) {
  return isStr(text) && text.split('\n').some(isTemplateLine);
}
// 剥 trailer + 模板行后还剩什么（空 = 该字段没有正文）
export function contentAfterNoise(text) {
  return String(text ?? '')
    .split('\n')
    .filter(l => !isTrailerLine(l) && !isTemplateLine(l))
    .join('\n')
    .trim();
}

// 近重复阈值：token 集合 Jaccard ≥ 0.8 且两边 token 数 ≥ 8（短文本一律交给 exact 重复判定，避免误报）。
export const NEAR_DUPLICATE_THRESHOLD = 0.8;
export const NEAR_DUPLICATE_MIN_TOKENS = 8;

const tokensOf = text => {
  const out = new Set();
  for (const t of normText(text).split(' ')) if (t.length >= 2) out.add(t);
  return out;
};
const jaccard = (a, b) => {
  let inter = 0;
  for (const t of a) if (b.has(t)) inter++;
  return inter / (a.size + b.size - inter);
};

const REASON_ORDER = new Map(NOISE_REASONS.map((r, i) => [r, i]));
const HIGH_REASONS = new Set(['trailer-only', 'template-only', 'duplicate-title', 'duplicate-why']);
const orderReasons = reasons => [...new Set(reasons)].sort((a, b) => REASON_ORDER.get(a) - REASON_ORDER.get(b));
const levelOf = reasons => (reasons.some(r => HIGH_REASONS.has(r)) ? 'high' : reasons.length ? 'low' : 'none');
// Map<key, value[]> 的追加（重复检测三处共用，免得各写一遍 get/set 体操）
const pushInto = (map, key, value) => {
  const arr = map.get(key);
  if (arr) arr.push(value);
  else map.set(key, [value]);
};

// 单条分类（无重复上下文）：trailer / 模板两口径。
// why 有正文时只看 why；why 缺省（或只有噪音）时，title 是唯一的正文载体，也纳入模板判定。
export function classifyAtom(atom) {
  const reasons = [];
  if (atom === null || typeof atom !== 'object' || Array.isArray(atom)) {
    return { level: 'none', reasons: [] };
  }
  const why = isStr(atom.why) ? atom.why : '';
  const title = isStr(atom.title) ? atom.title : '';
  if (why.trim() !== '') {
    if (contentAfterNoise(why) === '') {
      reasons.push(hasTrailerLines(why) ? 'trailer-only' : 'template-only');
    } else {
      if (hasTrailerLines(why)) reasons.push('trailer-mixed');
      if (hasTemplateLines(why)) reasons.push('template-mixed');
    }
  } else if (title.trim() !== '' && contentAfterNoise(title) === '') {
    reasons.push('template-only');            // 标题本身就是生成器样板 = 没有人写的正文
  }
  const ordered = orderReasons(reasons);
  return { level: levelOf(ordered), reasons: ordered };
}

// 批量分类（含重复摘要）：返回与输入**等长同序**的 [{level, reasons}]。
// 重复判定用规范化后的 title / why 精确相等 + token Jaccard 近重复；对组内每条都打标（顺序无关）。
export function classifyAtoms(atoms = []) {
  const list = Array.isArray(atoms) ? atoms : [];
  const base = list.map(classifyAtom);
  const titleGroups = new Map();
  const whyGroups = new Map();
  const tokenSets = list.map(() => null);
  const inverted = new Map();                     // token → atom indices（近重复的候选生成，避免 O(n²) 全比）
  list.forEach((a, i) => {
    if (a === null || typeof a !== 'object' || Array.isArray(a)) return;
    const t = normText(a.title);
    if (t) pushInto(titleGroups, t, i);
    const w = normText(a.why);
    if (w) pushInto(whyGroups, w, i);
    const tok = tokensOf(a.why);
    if (tok.size >= NEAR_DUPLICATE_MIN_TOKENS) {
      tokenSets[i] = tok;
      for (const tk of tok) pushInto(inverted, tk, i);
    }
  });
  const extra = list.map(() => []);
  for (const idxs of titleGroups.values()) {
    if (idxs.length > 1) for (const i of idxs) extra[i].push('duplicate-title');
  }
  for (const idxs of whyGroups.values()) {
    if (idxs.length > 1) for (const i of idxs) extra[i].push('duplicate-why');
  }
  const near = new Set();
  for (const [i, tok] of tokenSets.entries()) {
    if (!tok) continue;
    const cand = new Set();
    for (const tk of tok) for (const j of inverted.get(tk) ?? []) if (j !== i) cand.add(j);
    for (const j of cand) {
      const other = tokenSets[j];
      if (!other) continue;
      if (jaccard(tok, other) >= NEAR_DUPLICATE_THRESHOLD) { near.add(i); near.add(j); }
    }
  }
  for (const i of near) extra[i].push('near-duplicate-why');
  return list.map((_, i) => {
    const reasons = orderReasons([...base[i].reasons, ...extra[i]]);
    return { level: levelOf(reasons), reasons };
  });
}

// 分布（doctor 消费）：{high, low, none, reasons:{<code>: count}}。reasons 是诊断附加，键集只增。
export function noiseSummary(atoms = []) {
  const out = { high: 0, low: 0, none: 0, reasons: {} };
  for (const r of NOISE_REASONS) out.reasons[r] = 0;
  for (const { level, reasons } of classifyAtoms(atoms)) {
    out[level]++;
    for (const r of reasons) out.reasons[r]++;
  }
  return out;
}
